# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\first_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Input_First_2_dialog_UI(object):
    def setupUi(self, Input_First_2_dialog_UI):
        Input_First_2_dialog_UI.setObjectName("Input_First_2_dialog_UI")
        Input_First_2_dialog_UI.resize(577, 229)
        self.CardWidget_155 = CardWidget(Input_First_2_dialog_UI)
        self.CardWidget_155.setGeometry(QtCore.QRect(10, 10, 561, 211))
        self.CardWidget_155.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_155.setObjectName("CardWidget_155")
        self.gridLayout_87 = QtWidgets.QGridLayout(self.CardWidget_155)
        self.gridLayout_87.setObjectName("gridLayout_87")
        self.SubtitleLabel_658 = SubtitleLabel(self.CardWidget_155)
        self.SubtitleLabel_658.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_658.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_658.setObjectName("SubtitleLabel_658")
        self.gridLayout_87.addWidget(self.SubtitleLabel_658, 0, 0, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_155)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_87.addWidget(self.LineEdit_2, 1, 1, 1, 1)
        self.SubtitleLabel_659 = SubtitleLabel(self.CardWidget_155)
        self.SubtitleLabel_659.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_659.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_659.setObjectName("SubtitleLabel_659")
        self.gridLayout_87.addWidget(self.SubtitleLabel_659, 3, 0, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget_155)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout_87.addWidget(self.LineEdit_3, 3, 1, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_155)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_87.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.SubtitleLabel_657 = SubtitleLabel(self.CardWidget_155)
        self.SubtitleLabel_657.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_657.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_657.setObjectName("SubtitleLabel_657")
        self.gridLayout_87.addWidget(self.SubtitleLabel_657, 1, 0, 1, 1)

        self.retranslateUi(Input_First_2_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_First_2_dialog_UI)

    def retranslateUi(self, Input_First_2_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_First_2_dialog_UI.setWindowTitle(_translate("Input_First_2_dialog_UI", "Form"))
        self.SubtitleLabel_658.setText(_translate("Input_First_2_dialog_UI", "燃烧室燃气绝热指数k_heat"))
        self.SubtitleLabel_659.setText(_translate("Input_First_2_dialog_UI", "燃气气体常数R_gU/mol·K)"))
        self.SubtitleLabel_657.setText(_translate("Input_First_2_dialog_UI", "燃气流通系数K_c"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
