# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\first_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Input_First_1_dialog_UI(object):
    def setupUi(self, Input_First_1_dialog_UI):
        Input_First_1_dialog_UI.setObjectName("Input_First_1_dialog_UI")
        Input_First_1_dialog_UI.resize(633, 372)
        self.CardWidget_151 = CardWidget(Input_First_1_dialog_UI)
        self.CardWidget_151.setGeometry(QtCore.QRect(20, 10, 601, 351))
        self.CardWidget_151.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_151.setObjectName("CardWidget_151")
        self.gridLayout_85 = QtWidgets.QGridLayout(self.CardWidget_151)
        self.gridLayout_85.setObjectName("gridLayout_85")
        self.SubtitleLabel_646 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_646.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_646.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_646.setObjectName("SubtitleLabel_646")
        self.gridLayout_85.addWidget(self.SubtitleLabel_646, 4, 0, 1, 1)
        self.SubtitleLabel_648 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_648.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_648.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_648.setObjectName("SubtitleLabel_648")
        self.gridLayout_85.addWidget(self.SubtitleLabel_648, 5, 0, 1, 1)
        self.SubtitleLabel_650 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_650.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_650.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_650.setObjectName("SubtitleLabel_650")
        self.gridLayout_85.addWidget(self.SubtitleLabel_650, 3, 0, 1, 1)
        self.SubtitleLabel_647 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_647.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_647.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_647.setObjectName("SubtitleLabel_647")
        self.gridLayout_85.addWidget(self.SubtitleLabel_647, 1, 0, 1, 1)
        self.SubtitleLabel_649 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_649.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_649.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_649.setObjectName("SubtitleLabel_649")
        self.gridLayout_85.addWidget(self.SubtitleLabel_649, 2, 0, 1, 1)
        self.SubtitleLabel_645 = SubtitleLabel(self.CardWidget_151)
        self.SubtitleLabel_645.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_645.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_645.setObjectName("SubtitleLabel_645")
        self.gridLayout_85.addWidget(self.SubtitleLabel_645, 6, 0, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_151)
        self.LineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit.setText("")
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_85.addWidget(self.LineEdit, 1, 1, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_151)
        self.LineEdit_2.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit_2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_85.addWidget(self.LineEdit_2, 2, 1, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget_151)
        self.LineEdit_3.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit_3.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout_85.addWidget(self.LineEdit_3, 3, 1, 1, 1)
        self.LineEdit_4 = LineEdit(self.CardWidget_151)
        self.LineEdit_4.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout_85.addWidget(self.LineEdit_4, 4, 1, 1, 1)
        self.LineEdit_5 = LineEdit(self.CardWidget_151)
        self.LineEdit_5.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.gridLayout_85.addWidget(self.LineEdit_5, 5, 1, 1, 1)
        self.LineEdit_6 = LineEdit(self.CardWidget_151)
        self.LineEdit_6.setMinimumSize(QtCore.QSize(0, 31))
        self.LineEdit_6.setMaximumSize(QtCore.QSize(16777215, 31))
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.gridLayout_85.addWidget(self.LineEdit_6, 6, 1, 1, 1)

        self.retranslateUi(Input_First_1_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_First_1_dialog_UI)

    def retranslateUi(self, Input_First_1_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_First_1_dialog_UI.setWindowTitle(_translate("Input_First_1_dialog_UI", "Form"))
        self.SubtitleLabel_646.setText(_translate("Input_First_1_dialog_UI", "曲柄转角循环周期crankangle(°CA)"))
        self.SubtitleLabel_648.setText(_translate("Input_First_1_dialog_UI", "活塞半径R_piston(m)"))
        self.SubtitleLabel_650.setText(_translate("Input_First_1_dialog_UI", "连杆长度L（m）"))
        self.SubtitleLabel_647.setText(_translate("Input_First_1_dialog_UI", "曲柄连杆半径R(m)"))
        self.SubtitleLabel_649.setText(_translate("Input_First_1_dialog_UI", "曲柄转角round（r/min）"))
        self.SubtitleLabel_645.setText(_translate("Input_First_1_dialog_UI", "单缸功率g_power(kW)"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
