# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\first_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Input_First_4_dialog_UI(object):
    def setupUi(self, Input_First_4_dialog_UI):
        Input_First_4_dialog_UI.setObjectName("Input_First_4_dialog_UI")
        Input_First_4_dialog_UI.resize(618, 328)
        self.CardWidget_161 = CardWidget(Input_First_4_dialog_UI)
        self.CardWidget_161.setGeometry(QtCore.QRect(10, 10, 601, 311))
        self.CardWidget_161.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_161.setObjectName("CardWidget_161")
        self.gridLayout_91 = QtWidgets.QGridLayout(self.CardWidget_161)
        self.gridLayout_91.setObjectName("gridLayout_91")
        self.SubtitleLabel_674 = SubtitleLabel(self.CardWidget_161)
        self.SubtitleLabel_674.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_674.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_674.setObjectName("SubtitleLabel_674")
        self.gridLayout_91.addWidget(self.SubtitleLabel_674, 4, 1, 1, 1)
        self.StrongBodyLabel_32 = StrongBodyLabel(self.CardWidget_161)
        self.StrongBodyLabel_32.setMinimumSize(QtCore.QSize(300, 28))
        self.StrongBodyLabel_32.setMaximumSize(QtCore.QSize(451, 28))
        self.StrongBodyLabel_32.setObjectName("StrongBodyLabel_32")
        self.gridLayout_91.addWidget(self.StrongBodyLabel_32, 0, 1, 1, 1)
        self.SubtitleLabel_672 = SubtitleLabel(self.CardWidget_161)
        self.SubtitleLabel_672.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_672.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_672.setObjectName("SubtitleLabel_672")
        self.gridLayout_91.addWidget(self.SubtitleLabel_672, 2, 1, 1, 1)
        self.SubtitleLabel_673 = SubtitleLabel(self.CardWidget_161)
        self.SubtitleLabel_673.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_673.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_673.setObjectName("SubtitleLabel_673")
        self.gridLayout_91.addWidget(self.SubtitleLabel_673, 3, 1, 1, 1)
        self.SubtitleLabel_671 = SubtitleLabel(self.CardWidget_161)
        self.SubtitleLabel_671.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_671.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_671.setObjectName("SubtitleLabel_671")
        self.gridLayout_91.addWidget(self.SubtitleLabel_671, 1, 1, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_161)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_91.addWidget(self.LineEdit, 0, 2, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_161)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_91.addWidget(self.LineEdit_2, 1, 2, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget_161)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout_91.addWidget(self.LineEdit_3, 2, 2, 1, 1)
        self.LineEdit_4 = LineEdit(self.CardWidget_161)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout_91.addWidget(self.LineEdit_4, 3, 2, 1, 1)
        self.LineEdit_5 = LineEdit(self.CardWidget_161)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.gridLayout_91.addWidget(self.LineEdit_5, 4, 2, 1, 1)

        self.retranslateUi(Input_First_4_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_First_4_dialog_UI)

    def retranslateUi(self, Input_First_4_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_First_4_dialog_UI.setWindowTitle(_translate("Input_First_4_dialog_UI", "Form"))
        self.SubtitleLabel_674.setText(_translate("Input_First_4_dialog_UI", "活塞上行时润滑油供给比例pect_up"))
        self.StrongBodyLabel_32.setText(_translate("Input_First_4_dialog_UI", "注油孔距离下止点的距离position_hole(m)"))
        self.SubtitleLabel_672.setText(_translate("Input_First_4_dialog_UI", "润滑油消耗率g_oil(g/kW·h)\n"
""))
        self.SubtitleLabel_673.setText(_translate("Input_First_4_dialog_UI", "初始润滑油供给厚度h1(m)"))
        self.SubtitleLabel_671.setText(_translate("Input_First_4_dialog_UI", "润滑油供给宽度h_withd(m)"))
from qfluentwidgets import CardWidget, LineEdit, StrongBodyLabel, SubtitleLabel
