# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\first_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Input_First_3_dialog_UI(object):
    def setupUi(self, Input_First_3_dialog_UI):
        Input_First_3_dialog_UI.setObjectName("Input_First_3_dialog_UI")
        Input_First_3_dialog_UI.resize(600, 259)
        self.CardWidget_158 = CardWidget(Input_First_3_dialog_UI)
        self.CardWidget_158.setGeometry(QtCore.QRect(10, 10, 581, 241))
        self.CardWidget_158.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_158.setObjectName("CardWidget_158")
        self.gridLayout_89 = QtWidgets.QGridLayout(self.CardWidget_158)
        self.gridLayout_89.setObjectName("gridLayout_89")
        self.SubtitleLabel_664 = SubtitleLabel(self.CardWidget_158)
        self.SubtitleLabel_664.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_664.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_664.setObjectName("SubtitleLabel_664")
        self.gridLayout_89.addWidget(self.SubtitleLabel_664, 1, 0, 1, 1)
        self.SubtitleLabel_666 = SubtitleLabel(self.CardWidget_158)
        self.SubtitleLabel_666.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_666.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_666.setObjectName("SubtitleLabel_666")
        self.gridLayout_89.addWidget(self.SubtitleLabel_666, 0, 0, 1, 1)
        self.SubtitleLabel_665 = SubtitleLabel(self.CardWidget_158)
        self.SubtitleLabel_665.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_665.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_665.setObjectName("SubtitleLabel_665")
        self.gridLayout_89.addWidget(self.SubtitleLabel_665, 3, 0, 1, 1)
        self.SubtitleLabel_663 = SubtitleLabel(self.CardWidget_158)
        self.SubtitleLabel_663.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_663.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_663.setObjectName("SubtitleLabel_663")
        self.gridLayout_89.addWidget(self.SubtitleLabel_663, 2, 0, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_158)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_89.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_158)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_89.addWidget(self.LineEdit_2, 1, 1, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget_158)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout_89.addWidget(self.LineEdit_3, 2, 1, 1, 1)
        self.LineEdit_4 = LineEdit(self.CardWidget_158)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout_89.addWidget(self.LineEdit_4, 3, 1, 1, 1)

        self.retranslateUi(Input_First_3_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_First_3_dialog_UI)

    def retranslateUi(self, Input_First_3_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_First_3_dialog_UI.setWindowTitle(_translate("Input_First_3_dialog_UI", "Form"))
        self.SubtitleLabel_664.setText(_translate("Input_First_3_dialog_UI", "缸套表面粗糙度smgia_L(m)"))
        self.SubtitleLabel_666.setText(_translate("Input_First_3_dialog_UI", "缸套半径BR(m)"))
        self.SubtitleLabel_665.setText(_translate("Input_First_3_dialog_UI", "缸套材料泊松比v_L"))
        self.SubtitleLabel_663.setText(_translate("Input_First_3_dialog_UI", "缸套材料的杨氏模量E_L(Pa)"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
