# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\fourth_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Input_Fourth_2_dialog_UI(object):
    def setupUi(self, Input_Fourth_2_dialog_UI):
        Input_Fourth_2_dialog_UI.setObjectName("Input_Fourth_2_dialog_UI")
        Input_Fourth_2_dialog_UI.resize(511, 279)
        self.CardWidget_208 = CardWidget(Input_Fourth_2_dialog_UI)
        self.CardWidget_208.setGeometry(QtCore.QRect(10, 10, 491, 261))
        self.CardWidget_208.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_208.setObjectName("CardWidget_208")
        self.gridLayout_151 = QtWidgets.QGridLayout(self.CardWidget_208)
        self.gridLayout_151.setObjectName("gridLayout_151")
        self.SubtitleLabel_1011 = SubtitleLabel(self.CardWidget_208)
        self.SubtitleLabel_1011.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1011.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1011.setObjectName("SubtitleLabel_1011")
        self.gridLayout_151.addWidget(self.SubtitleLabel_1011, 1, 0, 1, 1)
        self.SubtitleLabel_1008 = SubtitleLabel(self.CardWidget_208)
        self.SubtitleLabel_1008.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1008.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1008.setObjectName("SubtitleLabel_1008")
        self.gridLayout_151.addWidget(self.SubtitleLabel_1008, 0, 0, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_208)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_151.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_208)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_151.addWidget(self.LineEdit_2, 1, 1, 1, 1)

        self.retranslateUi(Input_Fourth_2_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_Fourth_2_dialog_UI)

    def retranslateUi(self, Input_Fourth_2_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_Fourth_2_dialog_UI.setWindowTitle(_translate("Input_Fourth_2_dialog_UI", "Form"))
        self.SubtitleLabel_1011.setText(_translate("Input_Fourth_2_dialog_UI", "周期循环限定次数cyc_number"))
        self.SubtitleLabel_1008.setText(_translate("Input_Fourth_2_dialog_UI", "周期循环收敛精度cyc_imit"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
