# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\save_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class save_dialog_UI(object):
    def setupUi(self, save_dialog_UI):
        save_dialog_UI.setObjectName("save_dialog_UI")
        save_dialog_UI.resize(529, 291)
        self.CardWidget_223 = CardWidget(save_dialog_UI)
        self.CardWidget_223.setGeometry(QtCore.QRect(10, 10, 511, 271))
        self.CardWidget_223.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_223.setObjectName("CardWidget_223")
        self.gridLayout_158 = QtWidgets.QGridLayout(self.CardWidget_223)
        self.gridLayout_158.setObjectName("gridLayout_158")
        self.LineEdit = LineEdit(self.CardWidget_223)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_158.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.SubtitleLabel_1045 = SubtitleLabel(self.CardWidget_223)
        self.SubtitleLabel_1045.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1045.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1045.setObjectName("SubtitleLabel_1045")
        self.gridLayout_158.addWidget(self.SubtitleLabel_1045, 0, 0, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_223)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_158.addWidget(self.LineEdit_2, 1, 1, 1, 1)
        self.SubtitleLabel_1046 = SubtitleLabel(self.CardWidget_223)
        self.SubtitleLabel_1046.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1046.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1046.setObjectName("SubtitleLabel_1046")
        self.gridLayout_158.addWidget(self.SubtitleLabel_1046, 1, 0, 1, 1)

        self.retranslateUi(save_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(save_dialog_UI)

    def retranslateUi(self, save_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        save_dialog_UI.setWindowTitle(_translate("save_dialog_UI", "Form"))
        self.SubtitleLabel_1045.setText(_translate("save_dialog_UI", "命名此次参数输入"))
        self.SubtitleLabel_1046.setText(_translate("save_dialog_UI", "此次参数备注"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
