# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\third_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Input_Third_1_dialog_UI(object):
    def setupUi(self, Input_Third_1_dialog_UI):
        Input_Third_1_dialog_UI.setObjectName("Input_Third_1_dialog_UI")
        Input_Third_1_dialog_UI.resize(531, 370)
        self.CardWidget_202 = CardWidget(Input_Third_1_dialog_UI)
        self.CardWidget_202.setGeometry(QtCore.QRect(10, 10, 511, 351))
        self.CardWidget_202.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget_202.setObjectName("CardWidget_202")
        self.gridLayout_149 = QtWidgets.QGridLayout(self.CardWidget_202)
        self.gridLayout_149.setObjectName("gridLayout_149")
        self.SubtitleLabel_1000 = SubtitleLabel(self.CardWidget_202)
        self.SubtitleLabel_1000.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1000.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1000.setObjectName("SubtitleLabel_1000")
        self.gridLayout_149.addWidget(self.SubtitleLabel_1000, 0, 0, 1, 1)
        self.SubtitleLabel_998 = SubtitleLabel(self.CardWidget_202)
        self.SubtitleLabel_998.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_998.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_998.setObjectName("SubtitleLabel_998")
        self.gridLayout_149.addWidget(self.SubtitleLabel_998, 3, 0, 1, 1)
        self.SubtitleLabel_1003 = SubtitleLabel(self.CardWidget_202)
        self.SubtitleLabel_1003.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1003.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1003.setObjectName("SubtitleLabel_1003")
        self.gridLayout_149.addWidget(self.SubtitleLabel_1003, 1, 0, 1, 1)
        self.SubtitleLabel_1002 = SubtitleLabel(self.CardWidget_202)
        self.SubtitleLabel_1002.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_1002.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_1002.setObjectName("SubtitleLabel_1002")
        self.gridLayout_149.addWidget(self.SubtitleLabel_1002, 2, 0, 1, 1)
        self.SubtitleLabel_999 = SubtitleLabel(self.CardWidget_202)
        self.SubtitleLabel_999.setMinimumSize(QtCore.QSize(300, 28))
        self.SubtitleLabel_999.setMaximumSize(QtCore.QSize(451, 28))
        self.SubtitleLabel_999.setObjectName("SubtitleLabel_999")
        self.gridLayout_149.addWidget(self.SubtitleLabel_999, 4, 0, 1, 1)
        self.LineEdit = LineEdit(self.CardWidget_202)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout_149.addWidget(self.LineEdit, 0, 1, 1, 1)
        self.LineEdit_2 = LineEdit(self.CardWidget_202)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout_149.addWidget(self.LineEdit_2, 1, 1, 1, 1)
        self.LineEdit_3 = LineEdit(self.CardWidget_202)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout_149.addWidget(self.LineEdit_3, 2, 1, 1, 1)
        self.LineEdit_4 = LineEdit(self.CardWidget_202)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout_149.addWidget(self.LineEdit_4, 3, 1, 1, 1)
        self.LineEdit_5 = LineEdit(self.CardWidget_202)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.gridLayout_149.addWidget(self.LineEdit_5, 4, 1, 1, 1)

        self.retranslateUi(Input_Third_1_dialog_UI)
        QtCore.QMetaObject.connectSlotsByName(Input_Third_1_dialog_UI)

    def retranslateUi(self, Input_Third_1_dialog_UI):
        _translate = QtCore.QCoreApplication.translate
        Input_Third_1_dialog_UI.setWindowTitle(_translate("Input_Third_1_dialog_UI", "Form"))
        self.SubtitleLabel_1000.setText(_translate("Input_Third_1_dialog_UI", "润滑油粘压系数alpha"))
        self.SubtitleLabel_998.setText(_translate("Input_Third_1_dialog_UI", "润滑油系数B mu_B"))
        self.SubtitleLabel_1003.setText(_translate("Input_Third_1_dialog_UI", "润滑油粘度mu(Pa·s)"))
        self.SubtitleLabel_1002.setText(_translate("Input_Third_1_dialog_UI", "润滑油系数A mu_A"))
        self.SubtitleLabel_999.setText(_translate("Input_Third_1_dialog_UI", "润滑油密度rho(kg/s)"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
