# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\可视化编辑-不带结果.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SelectSaveDialog_UI(object):
    def setupUi(self, SelectSaveDialog_UI):
        SelectSaveDialog_UI.setObjectName("SelectSaveDialog_UI")
        SelectSaveDialog_UI.resize(452, 123)
        self.CardWidget = CardWidget(SelectSaveDialog_UI)
        self.CardWidget.setGeometry(QtCore.QRect(10, 10, 431, 101))
        self.CardWidget.setMinimumSize(QtCore.QSize(431, 101))
        self.CardWidget.setObjectName("CardWidget")
        self.IconWidget_23 = IconWidget(self.CardWidget)
        self.IconWidget_23.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.IconWidget_23.setObjectName("IconWidget_23")
        self.IconWidget_22 = IconWidget(self.CardWidget)
        self.IconWidget_22.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.IconWidget_22.setObjectName("IconWidget_22")
        self.SubtitleLabel_22 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_22.setGeometry(QtCore.QRect(60, 10, 171, 28))
        self.SubtitleLabel_22.setMinimumSize(QtCore.QSize(171, 28))
        self.SubtitleLabel_22.setObjectName("SubtitleLabel_22")
        self.SubtitleLabel_23 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_23.setGeometry(QtCore.QRect(60, 50, 171, 28))
        self.SubtitleLabel_23.setObjectName("SubtitleLabel_23")
        self.LineEdit = LineEdit(self.CardWidget)
        self.LineEdit.setGeometry(QtCore.QRect(240, 10, 181, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(self.CardWidget)
        self.LineEdit_2.setGeometry(QtCore.QRect(240, 50, 181, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")

        self.retranslateUi(SelectSaveDialog_UI)
        QtCore.QMetaObject.connectSlotsByName(SelectSaveDialog_UI)

    def retranslateUi(self, SelectSaveDialog_UI):
        _translate = QtCore.QCoreApplication.translate
        SelectSaveDialog_UI.setWindowTitle(_translate("SelectSaveDialog_UI", "Form"))
        self.SubtitleLabel_22.setText(_translate("SelectSaveDialog_UI", "命名此次可视化"))
        self.SubtitleLabel_23.setText(_translate("SelectSaveDialog_UI", "备注此次可视化"))
from qfluentwidgets import CardWidget, IconWidget, LineEdit, SubtitleLabel
