# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\可视化编辑-带结果.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ImportSaveDialog_UI(object):
    def setupUi(self, ImportSaveDialog_UI):
        ImportSaveDialog_UI.setObjectName("ImportSaveDialog_UI")
        ImportSaveDialog_UI.resize(450, 263)
        self.CardWidget = CardWidget(ImportSaveDialog_UI)
        self.CardWidget.setGeometry(QtCore.QRect(10, 10, 431, 241))
        self.CardWidget.setMinimumSize(QtCore.QSize(431, 241))
        self.CardWidget.setObjectName("CardWidget")
        self.IconWidget_23 = IconWidget(self.CardWidget)
        self.IconWidget_23.setGeometry(QtCore.QRect(10, 190, 31, 31))
        self.IconWidget_23.setObjectName("IconWidget_23")
        self.IconWidget_19 = IconWidget(self.CardWidget)
        self.IconWidget_19.setGeometry(QtCore.QRect(10, 70, 31, 31))
        self.IconWidget_19.setObjectName("IconWidget_19")
        self.IconWidget_22 = IconWidget(self.CardWidget)
        self.IconWidget_22.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.IconWidget_22.setObjectName("IconWidget_22")
        self.SubtitleLabel_22 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_22.setGeometry(QtCore.QRect(60, 150, 171, 28))
        self.SubtitleLabel_22.setObjectName("SubtitleLabel_22")
        self.SubtitleLabel_16 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_16.setGeometry(QtCore.QRect(60, 70, 171, 28))
        self.SubtitleLabel_16.setObjectName("SubtitleLabel_16")
        self.SubtitleLabel_23 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_23.setGeometry(QtCore.QRect(60, 190, 171, 28))
        self.SubtitleLabel_23.setObjectName("SubtitleLabel_23")
        self.LineEdit = LineEdit(self.CardWidget)
        self.LineEdit.setGeometry(QtCore.QRect(230, 70, 181, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(self.CardWidget)
        self.LineEdit_2.setGeometry(QtCore.QRect(230, 110, 181, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.LineEdit_3 = LineEdit(self.CardWidget)
        self.LineEdit_3.setGeometry(QtCore.QRect(230, 150, 181, 33))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.IconWidget_25 = IconWidget(self.CardWidget)
        self.IconWidget_25.setGeometry(QtCore.QRect(10, 110, 31, 31))
        self.IconWidget_25.setObjectName("IconWidget_25")
        self.LineEdit_4 = LineEdit(self.CardWidget)
        self.LineEdit_4.setGeometry(QtCore.QRect(230, 190, 181, 33))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.SubtitleLabel_21 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_21.setGeometry(QtCore.QRect(60, 110, 171, 28))
        self.SubtitleLabel_21.setObjectName("SubtitleLabel_21")
        self.SubtitleLabel = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel.setGeometry(QtCore.QRect(50, 20, 431, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")

        self.retranslateUi(ImportSaveDialog_UI)
        QtCore.QMetaObject.connectSlotsByName(ImportSaveDialog_UI)

    def retranslateUi(self, ImportSaveDialog_UI):
        _translate = QtCore.QCoreApplication.translate
        ImportSaveDialog_UI.setWindowTitle(_translate("ImportSaveDialog_UI", "Form"))
        self.SubtitleLabel_22.setText(_translate("ImportSaveDialog_UI", "命名此次可视化"))
        self.SubtitleLabel_16.setText(_translate("ImportSaveDialog_UI", "命名此次结果"))
        self.SubtitleLabel_23.setText(_translate("ImportSaveDialog_UI", "备注此次可视化"))
        self.SubtitleLabel_21.setText(_translate("ImportSaveDialog_UI", "备注此次结果"))
        self.SubtitleLabel.setText(_translate("ImportSaveDialog_UI", "你的结果来自本地，请同时保存参数！"))
from qfluentwidgets import CardWidget, IconWidget, LineEdit, SubtitleLabel
