# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GraduationDesign\source\UI\数据管理的对话框.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageDialog_UI(object):
    def setupUi(self, ManageDialog_UI):
        ManageDialog_UI.setObjectName("ManageDialog_UI")
        ManageDialog_UI.resize(423, 246)
        self.CardWidget = CardWidget(ManageDialog_UI)
        self.CardWidget.setGeometry(QtCore.QRect(10, 10, 401, 221))
        self.CardWidget.setObjectName("CardWidget")
        self.SubtitleLabel = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel.setGeometry(QtCore.QRect(20, 20, 211, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.SubtitleLabel_2 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(20, 70, 211, 28))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.SubtitleLabel_3 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_3.setGeometry(QtCore.QRect(20, 120, 211, 28))
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.SubtitleLabel_4 = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel_4.setGeometry(QtCore.QRect(20, 170, 211, 28))
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.LineEdit = LineEdit(self.CardWidget)
        self.LineEdit.setGeometry(QtCore.QRect(210, 20, 171, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(self.CardWidget)
        self.LineEdit_2.setGeometry(QtCore.QRect(210, 70, 171, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.LineEdit_3 = LineEdit(self.CardWidget)
        self.LineEdit_3.setGeometry(QtCore.QRect(210, 120, 171, 33))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.LineEdit_4 = LineEdit(self.CardWidget)
        self.LineEdit_4.setGeometry(QtCore.QRect(210, 170, 171, 33))
        self.LineEdit_4.setObjectName("LineEdit_4")

        self.retranslateUi(ManageDialog_UI)
        QtCore.QMetaObject.connectSlotsByName(ManageDialog_UI)

    def retranslateUi(self, ManageDialog_UI):
        _translate = QtCore.QCoreApplication.translate
        ManageDialog_UI.setWindowTitle(_translate("ManageDialog_UI", "Form"))
        self.SubtitleLabel.setText(_translate("ManageDialog_UI", "Subtitle label"))
        self.SubtitleLabel_2.setText(_translate("ManageDialog_UI", "Subtitle label"))
        self.SubtitleLabel_3.setText(_translate("ManageDialog_UI", "Subtitle label"))
        self.SubtitleLabel_4.setText(_translate("ManageDialog_UI", "Subtitle label"))
from qfluentwidgets import CardWidget, LineEdit, SubtitleLabel
